# Generated by Django 4.0.6 on 2022-07-31 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfinancialdata',
            old_name='payment_details',
            new_name='clark_file',
        ),
    ]
