# Generated by Django 4.0.6 on 2022-07-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0002_rename_payment_details_userfinancialdata_clark_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfinancialdata',
            old_name='clark_file',
            new_name='clerk_file',
        ),
    ]
